{% set version = '0.1-23' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rphylip
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Rphylip_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rphylip/Rphylip_{{ version }}.tar.gz
  sha256: 39bd1c9d2ce36f7a3e6c2bee12e9e064930f42de4a6d8f562427c34566acf84e
  patches:
    - rconsense_readmultixx_20190123.patch

build:
  number: 1006
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-ape >=3.0_10
  run:
    - r-base
    - r-ape >=3.0_10

test:
  commands:
    - $R -e "library('Rphylip')"           # [not win]
    - "\"%R%\" -e \"library('Rphylip')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/Rphylip/index.html
  license: GPL-2.0-or-later
  summary: Rphylip provides an R interface for the PHYLIP package. All users of Rphylip will
    thus first have to install the PHYLIP phylogeny methods program package (Felsenstein
    2013). See http://www.phylip.com for more  information about installing PHYLIP.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
   recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - bsennblad
